### ISSUE TITLE
Metrics Pipe

### ISSUE THREAD

**Issue by ManvithaPonnapati** [molecularmachines/moleculib#12]
Goal : Evaluate if a designed protein is a good design/a good binder.

Allan's Chemical Bond/Violition: 
- [ ] Wait for allan's push of the class 

Physics /SASA scores
- [ ] For any given PDB - if it's a filepath - call EvaluatePipe to return the rosetta scores
- [ ] Implement on the Datum the following functions from the Rosetta Potential - https://pubs.acs.org/doi/10.1021/acs.jctc.7b00125 - Use the pairwise distances to implement the equations in the paper - may not be easy because i am not sure if getting w_conn is as easy but might work for any things that rosetta borrows from CHARMM

**Comment by ManvithaPonnapati** [comment]
@AllanSCosta  If you want to add any other metrics we should have

**Comment by AllanSCosta** [comment]
I have a proposal interface: 
```
- metrics
- base.py -> Defines the Metric, and the MetricsPipe class
- protein/
  - secondary_structure.py
  - 
```
When one wants to use:

```
from moleculib.metrics import MetricsPipe, SecondaryStructureAnnotate
metrics_pipe = MetricsPipe(
  SecondaryStructureAnnotate(params),
  ...
)
datum = ProteinDatum.fetch_pdb_id('1L2Y')
datum_metrics = metrics_pipe(datum) # returns dictionary of metrics
```

Let me know your thoughts @ManvithaPonnapati @MatV7 

It would be great to keep metrics operating on ProteinDatum instead of directly on PDB files – although not all metrics can be made so I believe (@ManvithaPonnapati correct me if I'm wrong). This would be for the sake of being able to use some metrics in training pipeline without needing to do files I/O

**Comment by MatV7** [comment]
@AllanSCosta I have been using the annotations from a gb file using the biotite.sequence.io.genbank to generate the secondary sequences information since the gb file has all the secondary sequence information neetly packaged, have not been using a pdb file. Is this alright?


Edit: Actually, now that I compare the PDB information on helices to that of the gb files, it seems there are slight differences, i.e. PDB indicates a helix from 61-71 whilst gb indicates from 62-69; will just stick to the PDB information and try using ProteinDatum.
